# For OpenAI:
#spring.application.name=SpringAI-Demo
#spring.ai.openai.api-key=${OPENAI_API_KEY}

# For Groq:
spring.application.name=SpringAI-Continued
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=openai/gpt-oss-120b