# For OpenAI:
#spring.application.name=SpringAI-Demo
#spring.ai.openai.api-key=${OPENAI_API_KEY}

# For Groq:
spring.application.name=SpringAI-Continued
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# Database configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_ai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

spring.ai.chat.memory.repository.jdbc.initialize-schema=always